server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5    #take or update service list per 5 sec
zuul:
  prefix: /api
  routes:
    item-service: /item/**    #route to goods's micro service
    search-service: /search/**