server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.101:9300
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10     # pull service time
  instance:
    lease-renewal-interval-in-seconds: 5    #heartbeat time
    lease-expiration-duration-in-seconds: 15 #invalid time
logging:
  level:
    org.springframework.web: debug      # add log
