server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.56.101
    port: 5672    #can ignore,default is 5672
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5    #heartbeat time
    lease-expiration-duration-in-seconds: 15 #invalid time
mybatis:
  type-aliases-package: com.leyou.item.pojo
logging:
  level:
    org.springframework.web: debug      # add log