server:
  port: 10010
spring:
  application:
    name: study-zuul
zuul:
  routes:
    #service-provider: /service-provider/** #route name,usually service name
    service-provider: /user/** #route name,usually service name
    service-consumer: /consumer/**
      # path: /service-provider/**
      # url: http://localhost:8083
      # serviceId: service-provider
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka