server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false           #don't regist to self
    fetch-registry: false                 #don't take service list
  server:
    enable-self-preservation: false         #close self protection
    eviction-interval-timer-in-ms: 10000    #clean the invalid link per 10 sec